# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./binary:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Admin123@

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
