# Use root/example as user/password credentials
version: '3.1'

services:
  postgress_db:
    image: postgres:14.3
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./binary/postgres14:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: Admin123@

  postgres_adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
